name: Cinemagraph.nl
favicon: null
layout_spectrum: 0.6255319
typography_spectrum: 0.2276596
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#191315'
    - '#5C1703'
    - '#F3DF42'
    - '#E05D16'
    - '#FCFA9A'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0
purpose: []
