layout_spectrum: 1
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2808511
  lightness: 0.5085106
  brandStrength: 0.8212766
  brandColors:
    - '#181718'
    - '#D7BCAC'
    - '#885C4B'
    - '#A3A3A3'
  rhythmicContrast: 0.75
typography_spectrum: 0.3659574
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
name: Cinemagraph.nl
