favicon: null
name: Cinemagraph.nl
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.2808511
  brandStrength: 0.806383
  rhythmicContrast: 0
  brandColors:
    - '#181718'
    - '#D7BCAC'
    - '#885C4B'
    - '#A3A3A3'
  lightness: 0.4595745
typography_spectrum: 0.2276596
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4021277
analytics:
  twitter: null
  google: null
  facebook: null
