analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.506383
  brandStrength: 1
  lightness: 0.2425532
  brandColors:
    - '#191315'
    - '#5C1703'
    - '#F3DF42'
    - '#E05D16'
    - '#FCFA9A'
  rhythmicContrast: 0.506383
typography_spectrum: 0.2276596
cta:
  bucket: null
  version: null
  domain: null
layout_spectrum: 0.4021277
favicon: null
name: Cinemagraph.nl
