name: Cinemagraph.nl
favicon: null
layout_spectrum: 0.4021277
typography_spectrum: 0.2276596
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ddb9ad'
    - '#93a396'
    - '#766a6a'
    - '#a57d7d'
    - '#984a58'
  brandStrength: 0.806383
  lightness: 0.4595745
  saturation: 0.2808511
  rhythmicContrast: 0
purpose: []
