name: Cinemagraph.nl
favicon: null
layout_spectrum: 1
typography_spectrum: 0.37937
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#140f0b'
    - '#725f52'
    - '#bd9373'
    - '#564830'
    - '#deb89d'
  brandStrength: 0.3125
  lightness: 0.1875
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
